import type { ProductSummary } from '../types';
import { imgs, COMMON_HOTLINE, buildArticle, rf2470Paths } from './utils';

const CDN = 'https://mayanhvietnam.com';

export const lenses: ProductSummary[] = [
  // ── 1. Canon RF 24-70mm f/2.8L IS USM ───────────────────────────────────
  {
    id: 'p5',
    slug: 'ong-kinh-canon-rf-2470-f28-l-is-usm-chinh-hang',
    name: 'Ống kính Canon RF 24-70mm f/2.8L IS USM — Chính hãng',
    thumbnail: rf2470Paths.avatar,
    images: imgs(rf2470Paths.avatar, rf2470Paths.previews, 'Canon RF 24-70mm f/2.8L IS USM'),
    price: 48900000,
    originalPrice: 48900000,
    badges: [{ type: 'hot', label: 'Professional' }, { type: 'new', label: 'Chính hãng' }],
    rating: { average: 4.9, count: 94 },
    isUsed: false,
    brand: 'Canon',
    mount: 'Canon RF',
    availability: 'in_stock',
    category: 'ong-kinh',
    shortSpecs: [
      '24-70mm f/2.8L IS USM',
      'IS 5-stop',
      'Nano USM motor',
      'L-series cao cấp',
      'Filter 82mm',
      '21 thấu kính / 15 nhóm',
      '9 lá khẩu bokeh tròn',
      'Magnification 0.3×',
    ],
    description:
      'Ống kính Canon RF 24-70mm f/2.8L IS USM chính hãng — zoom chuẩn L-series cao cấp với khẩu độ tối đa f/2.8 không đổi qua dải zoom. Phù hợp mọi thể loại: chân dung, du lịch, sự kiện, cưới.',
    highlights: [
      'L-series cao cấp — chống bụi, chống nước',
      'Khẩu f/2.8 không đổi — chụp thiếu sáng vượt trội',
      'Chống rung quang học IS 5 stops',
      'Motor Nano USM — lấy nét nhanh, êm',
      'Lớp phủ ASC + Air Sphere Coating',
      'Filter 82mm — đường kính lớn',
    ],
    specs: [
      {
        group: 'Quang học',
        items: [
          { label: 'Mount', value: 'Canon RF (Full-frame mirrorless)' },
          { label: 'Focal length', value: '24-70mm' },
          { label: 'Khẩu tối đa', value: 'f/2.8' },
          { label: 'Khẩu tối thiểu', value: 'f/22' },
          { label: 'Cấu tạo quang học', value: '21 thấu kính / 15 nhóm' },
          { label: 'Số lá khẩu', value: '9 (bo tròn)' },
          { label: 'Magnification', value: '0.3×' },
        ],
      },
      {
        group: 'Lấy nét',
        items: [
          { label: 'Hệ thống AF', value: 'Nano USM' },
          { label: 'Khoảng cách lấy nét tối thiểu', value: '0.21 - 0.38m' },
        ],
      },
      {
        group: 'Vật lý',
        items: [
          { label: 'Filter size', value: '82mm' },
          { label: 'Trọng lượng', value: '900g' },
          { label: 'Kích thước', value: 'Φ88.5 × 122.7 mm' },
          { label: 'Chống chịu thời tiết', value: 'Có — kết cấu chống bụi/ẩm' },
        ],
      },
    ],
    packageIncludes: [
      '1× Ống kính Canon RF 24-70mm f/2.8L IS USM',
      '1× Cản hoa',
      '1× Nắp trước E-82 II',
      '1× Nắp sau RF',
      'Bao đựng + Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Canon RF 24-70mm f/2.8L IS USM — Ống kính standard zoom đỉnh cao',
      readTime: 8,
      sections: [
        { heading: 'Tổng quan', content: 'Canon RF 24-70mm f/2.8L IS USM là ống kính zoom standard cao cấp nhất trong hệ sinh thái RF, thuộc dòng L-series danh tiếng. Với khẩu độ f/2.8 không đổi và chống rung IS 5 stops, đây là lựa chọn hàng đầu cho nhiếp ảnh gia chuyên nghiệp.' },
        { heading: 'Chất lượng quang học', content: '21 thấu kính / 15 nhóm, bao gồmSuper UD và UD elements giúp giảm quang sai màu. Lớp phủ ASC (Air Sphere Coating) + Sub Wavelength Structure Coating chống flare và ghosting hiệu quả. 9 lá khẩu bokeh tròn cho hậu cảnh mượt mà.' },
        { heading: 'Tốc độ lấy nét', content: 'Motor Nano USM kết hợp khả năng lấy nét nhanh và êm — lý tưởng cho cả ảnh tĩnh và video. Khoảng cách lấy nét tối thiểu 0.21m (wide) cho phép chụp cận cảnh ấn tượng.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Chất lượng quang học L-series đỉnh cao. IS 5 stops mạnh nhất dòng zoom standard. Nano USM nhanh, êm. Khẩu f/2.8 không đổi.\n\n**Nhược điểm:** Giá cao (48.9 triệu). Nặng 900g. Filter 82mm đắt.' },
      ],
    }),
    variants: [
      { id: 'rf2470-f28-is', name: 'Chính hãng Canon VN', price: 48900000 },
    ],
    sku: 'RF-2470-28L-IS-USM',
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/ong-kinh-canon-rf-24-70mm-f-2-8l-is-usm-chinh-hang_lens-230210234357844',
    scrapedAt: '2026-07-09',
  },

  // ── 2. Canon RF 50mm f/1.8 STM ──────────────────────────────────────────
  {
    id: 'p10',
    slug: 'ong-kinh-canon-rf-50mm-f1-8-stm-chinh-hang',
    name: 'Ống kính Canon RF 50mm f/1.8 STM — Chính hãng',
    thumbnail: `${CDN}/image-data/san-pham/24-08/24-08-03/240803094047373/avatar/638847186653427391_canon-rf-50mm-f1-8-stm-chinh-hang.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/24-08/24-08-03/240803094047373/avatar/638847186653427391_canon-rf-50mm-f1-8-stm-chinh-hang.jpg`,
      [
        '638894765689925506.jpg',
        '638894769934751143.jpg',
        '638894766157268548.jpg',
        '638894766899566625.jpg',
      ].map((f) => `${CDN}/image-data/san-pham/24-08/24-08-03/240803094047373/hinh-bai-viet/${f}`),
      'Canon RF 50mm f/1.8 STM',
    ),
    price: 5990000,
    originalPrice: 5990000,
    badges: [{ type: 'hot', label: 'Best seller' }, { type: 'new', label: 'Giá tốt' }],
    rating: { average: 4.8, count: 192 },
    isUsed: false,
    brand: 'Canon',
    mount: 'Canon RF',
    availability: 'in_stock',
    category: 'ong-kinh',
    shortSpecs: [
      '50mm f/1.8 STM',
      '7 thấu kính / 6 nhóm',
      '7 lá khẩu bokeh',
      'Filter 43mm',
      'Trọng lượng 160g',
      'Khoảng cách lấy nét 0.30m',
    ],
    description: 'Canon RF 50mm f/1.8 STM — "nifty fifty" kinh điển cho ngàm RF, khẩu độ lớn f/1.8 lý tưởng cho chân dung và chụp thiếu sáng, giá rất phải chăng.',
    highlights: [
      'f/1.8 nhanh — portrait đẹp bokeh mượt',
      'STM Motor — lấy nét êm, không rung khi quay',
      '160g nhẹ — ống lens nhỏ gọn dòng RF',
    ],
    specs: [
      { group: 'Quang học', items: [
        { label: 'Focal length', value: '50mm' },
        { label: 'Khẩu tối đa', value: 'f/1.8' },
        { label: 'Khẩu tối thiểu', value: 'f/22' },
        { label: 'Cấu tạo', value: '7 thấu kính / 6 nhóm — 7 lá khẩu bokeh' },
      ]},
      { group: 'Lấy nét', items: [
        { label: 'Motor', value: 'STM — stepping motor' },
        { label: 'Khoảng cách lấy nét', value: '0.30m' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Mount', value: 'Canon RF (APS-C / Full-frame)' },
        { label: 'Filter size', value: '43mm' },
        { label: 'Trọng lượng', value: '160g' },
        { label: 'Kích thước', value: 'Φ69.6 × 40.7 mm' },
      ]},
    ],
    packageIncludes: [
      '1× Lens Canon RF 50mm f/1.8 STM',
      '1× Nắp trước E-43',
      '1× Nắp sau RF',
      'Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Canon RF 50mm f/1.8 STM — Nifty fifty giá trị nhất Canon RF',
      readTime: 6,
      sections: [
        { heading: 'Tổng quan', content: 'Canon RF 50mm f/1.8 STM là ống kính prime giá phải chăng nhất cho hệ ngàm Canon RF. Với khẩu độ lớn f/1.8 và motor STM êm ái, đây là lựa chọn lý tưởng cho người mới bắt đầu và nhiếp ảnh gia cần một ống kính nhẹ, linh hoạt.' },
        { heading: 'Chất lượng hình ảnh', content: '7 thấu kính / 6 nhóm, bao gồm 1 aspherical element giúp giảm quang sai. Bokeh mượt từ 7 lá khẩu tròn. f/1.8 cho phép tách nền đẹp và chụp thiếu sáng tốt.' },
        { heading: 'Motor STM', content: 'Motor Stepping Motor (STM) cho lấy nét êm ái, không nhảy — lý tưởng khi quay video. AF không quá nhanh nhưng đủ tốt cho chân dung và street photography.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Nhẹ chỉ 160g. f/1.8 bokeh đẹp. Giá phải chăng 5.9 triệu. STM êm khi quay video.\n\n**Nhược điểm:** Không có IS. AF motor chậm hơn USM. Filter nhỏ 43mm.' },
      ],
    }),
    variants: [
      { id: 'rf50-f18', name: 'Chính hãng Canon VN', price: 5990000 },
    ],
    sku: 'RF50F18STM',
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/ong-kinh-canon-rf-50mm-f1-8-stm-chinh-hang_lens-240803094047373',
    scrapedAt: '2026-07-09',
  },

  // ── 3. Sony FE 70-200mm f/2.8 GM OSS II ────────────────────────────────
  {
    id: 'p11',
    slug: 'ong-kinh-sony-fe-70-200mm-f2-8-gm-ii-oss-chinh-hang',
    name: 'Ống kính Sony FE 70-200mm f/2.8 GM OSS II — Chính hãng',
    thumbnail: `${CDN}/image-data/san-pham/24-08/24-08-03/240803094242227/avatar/638692469929544019_ong-kinh-sony-fe-70-200mm-f2-8-gm-ii-oss.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/24-08/24-08-03/240803094242227/avatar/638692469929544019_ong-kinh-sony-fe-70-200mm-f2-8-gm-ii-oss.jpg`,
      [],
      'Sony FE 70-200mm f/2.8 GM OSS II',
    ),
    price: 62900000,
    originalPrice: 62900000,
    badges: [{ type: 'hot', label: 'Flagship' }, { type: 'new', label: 'GM II' }],
    rating: { average: 5.0, count: 28 },
    isUsed: false,
    brand: 'Sony',
    mount: 'Sony E',
    availability: 'in_stock',
    category: 'ong-kinh',
    shortSpecs: [
      '70-200mm f/2.8 GM II',
      'XD Linear Motor × 4',
      'OSS 5.5 stops',
      '1045g nhẹ nhất dòng f/2.8',
      'XA Element bokeh đỉnh cao',
      'Filter 77mm',
    ],
    highlights: [
      'GM II thế hệ mới — 1045g nhẹ nhất dòng f/2.8',
      'XA Element — bokeh mượt đỉnh cao',
      '4× XD Linear Motor — AF cực nhanh',
    ],
    specs: [
      { group: 'Quang học', items: [
        { label: 'Focal length', value: '70 – 200mm' },
        { label: 'Khẩu tối đa', value: 'f/2.8' },
        { label: 'Khẩu tối thiểu', value: 'f/22' },
        { label: 'Cấu tạo', value: '17 thấu kính / 14 nhóm' },
      ]},
      { group: 'Lấy nét & Ổn định', items: [
        { label: 'Motor AF', value: 'XD Linear Motor × 4' },
        { label: 'Chống rung', value: 'OSS — Optical SteadyShot 5.5 stops' },
        { label: 'Khoảng cách lấy nét', value: '0.4m (wide) / 0.82m (tele)' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Mount', value: 'Sony E (Full-frame / APS-C)' },
        { label: 'Filter size', value: '77mm' },
        { label: 'Trọng lượng', value: '1045g' },
        { label: 'Kích thước', value: '88 × 200mm' },
        { label: 'Chống chịu thời tiết', value: 'Có — dust/moisture resistant' },
      ]},
    ],
    packageIncludes: [
      '1× Lens Sony FE 70-200mm f/2.8 GM II OSS',
      '1× Nắp trước ALC-R1EM',
      '1× Nắp sau',
      '1× Hood ALC-SH157',
      'Bao đựng tripod mount',
      'Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Sony FE 70-200mm f/2.8 GM II — Tele zoom flagship nhẹ nhất',
      readTime: 7,
      sections: [
        { heading: 'Tổng quan', content: 'Sony FE 70-200mm f/2.8 GM OSS II là thế hệ II của ống kính tele zoom flagship Sony, với trọng lượng giảm 29% xuống chỉ 1045g — nhẹ nhất trong phân khúc f/2.8 70-200mm. 4 motor XD Linear cho AF cực nhanh, XA Element cho bokeh đỉnh cao.' },
        { heading: 'Chất lượng quang học', content: '17 thấu kính / 14 nhóm, bao gồm XA (extreme aspherical), ED và Super ED elements. Bokeh mượt mà từ 9 lá khẩu tròn. Magnification 0.3× ở vị trí wide.' },
        { heading: 'AF và ổn định', content: '4× XD Linear Motor cho AF cực nhanh, gần như im lặng — lý tưởng cho sự kiện, thể thao. OSS 5.5 stops kết hợp IBIS trên机身 cho khả năng chống rung tổng hợp lên đến 7.5 stops.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Nhẹ nhất dòng f/2.8 (1045g). AF XD Linear cực nhanh. OSS 5.5 stops. Chống chịu thời tiết.\n\n**Nhược điểm:** Giá rất cao (62.9 triệu). Không có zoom ring rubber grip. Cần body Sony full-frame để phát huy hết.' },
      ],
    }),
    variants: [
      { id: 'sel70200gm2', name: 'Chính hãng Sony VN', price: 62900000 },
    ],
    sku: 'SEL70200GM2',
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/ong-kinh-sony-fe-70-200mm-f2-8-gm-ii-oss-chinh-hang_lens-240803094242227',
    scrapedAt: '2026-07-09',
  },

  // ── 4. Nikon Z 24-70mm f/2.8 S II ──────────────────────────────────────
  {
    id: 'p13',
    slug: 'ong-kinh-nikon-z-2470-f28-s-ii',
    name: 'Ống kính Nikon Z 24-70mm f/2.8 S II — Chính hãng',
    thumbnail: `${CDN}/image-data/san-pham/25-09/25-09-22/250922103851025/avatar/638941343754731632_ong-kinh-nikon-z-24-70mm-f-2-8-s-ii.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/25-09/25-09-22/250922103851025/avatar/638941343754731632_ong-kinh-nikon-z-24-70mm-f-2-8-s-ii.jpg`,
      [
        '638950128273248847.jpg',
        '638950128555460639.jpg',
        '638950128802189315.jpg',
        '638950129043788921.jpg',
      ].map((f) => `${CDN}/image-data/san-pham/25-09/25-09-22/250922103851025/hinh-bai-viet/${f}`),
      'Nikon Z 24-70mm f/2.8 S II',
    ),
    price: 69000000,
    originalPrice: 69000000,
    badges: [{ type: 'hot', label: 'Professional' }, { type: 'new', label: 'S-Line II' }],
    rating: { average: 4.9, count: 31 },
    isUsed: false,
    brand: 'Nikon',
    mount: 'Nikon Z',
    availability: 'in_stock',
    category: 'ong-kinh',
    shortSpecs: [
      '24-70mm f/2.8 S II',
      'S-Line cao cấp nhất',
      'AF motor Silky Swift VCM',
      'Trọng lượng 805g',
      'Filter 82mm',
      'Chống bụi/ẩm',
    ],
    highlights: [
      'S-Line II thế hệ mới — nhỏ gọn hơn, AF nhanh hơn',
      'Silky Swift VCM motor — lấy nét cực nhanh, gần như im lặng',
      'Chất lượng quang học đỉnh cao S-Line',
    ],
    specs: [
      { group: 'Quang học', items: [
        { label: 'Focal length', value: '24-70mm' },
        { label: 'Khẩu tối đa', value: 'f/2.8' },
        { label: 'Khẩu tối thiểu', value: 'f/22' },
        { label: 'Cấu tạo', value: '17 thấu kính / 15 nhóm' },
        { label: 'Số lá khẩu', value: '9 (bo tròn)' },
      ]},
      { group: 'Lấy nét', items: [
        { label: 'Motor AF', value: 'Silky Swift VCM' },
        { label: 'Khoảng cách lấy nét', value: '0.24m (wide) / 0.33m (tele)' },
        { label: 'Magnification', value: '0.22×' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Mount', value: 'Nikon Z (Full-frame)' },
        { label: 'Filter size', value: '82mm' },
        { label: 'Trọng lượng', value: '805g' },
        { label: 'Chống chịu thời tiết', value: 'Có — dust/moisture resistant' },
      ]},
    ],
    packageIncludes: [
      '1× Ống kính Nikon Z 24-70mm f/2.8 S II',
      '1× Cản hoa HB-89',
      '1× Nắp trước LC-82B',
      '1× Nắp sau LF-N1',
      'Bao đựng CL-C2',
      'Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Nikon Z 24-70mm f/2.8 S II — Standard zoom mới nhất Nikon',
      readTime: 7,
      sections: [
        { heading: 'Tổng quan', content: 'Nikon Z 24-70mm f/2.8 S II là thế hệ II của ống kính zoom standard cao cấp nhất Nikon cho hệ Z-mount. Nhỏ gọn hơn thế hệ I, motor AF Silky Swift VCM nhanh hơn đáng kể, chất lượng quang học S-Line đỉnh cao.' },
        { heading: 'Thiết kế mới', content: 'Trọng lượng 805g — nhẹ hơn thế hệ I,(filter 82mm). Vòng lấy nét rộng, mượt. Các nút tùy chỉnh customizable trên thân ống kính. Kết cấu chống bụi/ẩm toàn diện.' },
        { heading: 'AF Motor Silky Swift VCM', content: 'Motor Voice Coil Motor (VCM) mới cho AF cực nhanh, gần như im lặng. Phù hợp cho cả sự kiện, cưới, quay video cần âm thanh trong trẻo.' },
        { heading: 'Ưu và Nhược điểm', content: '**Ưu điểm:** Nhỏ gọn hơn thế hệ I. AF VCM cực nhanh. S-Line quang học đỉnh cao. Filter 82mm tiện lợi.\n\n**Nhược điểm:** Giá rất cao (69 triệu). Chỉ tương thích Nikon Z-mount.' },
      ],
    }),
    variants: [
      { id: 'z2470-s2', name: 'Chính hãng Nikon VN', price: 69000000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/ong-kinh-nikon-z-24-70mm-f-2-8-s-ii_lens-250922103851025',
    scrapedAt: '2026-07-10',
  },
];
