import type { ProductSummary } from '../types';
import { imgs, COMMON_HOTLINE, buildArticle } from './utils';

const CDN = 'https://mayanhvietnam.com';

export const cinema: ProductSummary[] = [
  // ── 1. Sony FX30 Cinema Line ────────────────────────────────────────────
  {
    id: 'p18',
    slug: 'sony-fx30-cinema-line',
    name: 'Sony FX30 Cinema Line — Body Only',
    thumbnail: `${CDN}/image-data/san-pham/24-08/24-08-29/240829180801135/avatar/638722123731263546_may-quay-phim-sony-ilmefx30-chinh-hang.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/24-08/24-08-29/240829180801135/avatar/638722123731263546_may-quay-phim-sony-ilmefx30-chinh-hang.jpg`,
      [],
      'Sony FX30 Cinema Line',
    ),
    price: 43990000,
    originalPrice: 43990000,
    badges: [{ type: 'hot', label: 'Cinema Line' }, { type: 'new', label: 'Chính hãng' }],
    rating: { average: 4.8, count: 33 },
    isUsed: false,
    brand: 'Sony',
    mount: 'Sony E',
    availability: 'in_stock',
    category: 'may-quay-phim',
    shortSpecs: [
      'APS-C Exmor R 26MP',
      '4K 120p 10-bit 4:2:2',
      'S-Cinetone / S-Log3',
      'Active Mode IBIS',
      'Sony E-mount',
      '646g với XLR handle',
    ],
    description: 'Máy quay Cinema Line APS-C với cảm biến 26MP, quay 4K 120p 10-bit 4:2:2, hỗ trợ S-Cinetone và Log shooting chuyên nghiệp.',
    highlights: [
      'Cảm biến APS-C Exmor R 26MP',
      '4K 120p 10-bit 4:2:2 — slow motion cực mượt',
      'S-Cinetone + S-Log3 cho grading chuyên nghiệp',
      'Active Mode IBIS chống rung khi quay',
    ],
    specs: [
      { group: 'Cảm biến & Quay', items: [
        { label: 'Cảm biến', value: 'APS-C Exmor R 26MP' },
        { label: 'Video', value: '4K 120p / FHD 240p, 10-bit 4:2:2' },
        { label: 'Log profile', value: 'S-Log3 / S-Cinetone / HLG' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Chống rung', value: 'Active Mode IBIS 5 trục' },
        { label: 'Ngàm ống kính', value: 'Sony E' },
        { label: 'Trọng lượng', value: '646g (với XLR handle)' },
        { label: 'Kích thước', value: '129.7 × 77.8 × 84.5 mm' },
      ]},
    ],
    packageIncludes: [
      '1× Sony FX30 body',
      '1× XLR Handle Unit',
      '1× Pin NP-FZ100',
      '1× Sạc',
      '1× Cáp USB-C',
      'Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Sony FX30 — Cinema Line APS-C cho filmmaker',
      readTime: 8,
      sections: [
        { heading: 'Tổng quan', content: 'Sony FX30 là máy quay Cinema Line APS-C, thuộc dòng Sony Cinema Line dành cho filmmaker chuyên nghiệp và content creator. Với cảm biến 26MP, 4K 120p 10-bit 4:2:2, S-Cinetone và S-Log3, FX30 cung cấp chất lượng cinema trong thân máy nhỏ gọn.' },
        { heading: 'Quay video cinema', content: '4K 120p 10-bit 4:2:2 — chất lượng cinema trong tầm giá. S-Cinetone cho màu đẹp ngay khi quay, S-Log3 cho grading chuyên nghiệp. Dual-base ISO 800/2500 cho dynamic range cực rộng.' },
        { heading: 'XLR Handle & âm thanh', content: 'Tay cầm XLR Handle Unit đi kèm cung cấp 2 input XLR/TRS cho micro chuyên nghiệp. Audio 4-channel 24-bit recording. Active Mode IBIS chống rung khi quay cầm tay.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** 4K 120p 10-bit 4:2:2 giá phải chăng. S-Cinetone + S-Log3. XLR Handle tích hợp. Active IBIS. Cùng ngàm E với Sony A7.\n\n**Nhược điểm:** Cảm biến APS-C không có chất lượng low-light như full-frame. Không có EVF lớn như FX3. Chỉ có 1 khe CFexpress Type A.' },
      ],
    }),
    variants: [
      { id: 'fx30-handle', name: 'Kèm XLR Handle Unit', price: 46990000, discountPrice: 43990000 },
      { id: 'fx30-body', name: 'Body Only', price: 39990000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/may-quay-phim-sony-ilmefx30-chinh-hang_may-quay-phim-240829180801135',
    scrapedAt: '2026-07-09',
  },

  // ── 2. Sony FX3 ────────────────────────────────────────────────────────
  {
    id: 'p19',
    slug: 'sony-fx3-full-frame-cinema-line',
    name: 'Sony FX3 Full-Frame Cinema Line — Body',
    thumbnail: `${CDN}/image-data/san-pham/23-02/23-02-10/230210230000001/avatar/01_may-quay-sony-fx3-cinema-line.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/23-02/23-02-10/230210230000001/avatar/01_may-quay-sony-fx3-cinema-line.jpg`,
      [],
      'Sony FX3 Cinema Line',
    ),
    price: 79900000,
    originalPrice: 79900000,
    badges: [{ type: 'hot', label: 'Full-frame Cinema' }, { type: 'new', label: 'Mới 100%' }],
    rating: { average: 4.9, count: 47 },
    isUsed: false,
    brand: 'Sony',
    mount: 'Sony E',
    availability: 'in_stock',
    category: 'may-quay-phim',
    shortSpecs: [
      'Full-frame Exmor R 12.1MP (video)',
      '4K 120p 10-bit 4:2:2',
      '16-bit RAW HDMI out',
      'Dual-base ISO 800/12800',
      'Active IBIS',
      'Tích hợp quạt tản nhiệt',
      'XLR Handle đi kèm',
    ],
    description: 'Máy quay Cinema Line full-frame nhỏ gọn nhất của Sony. Quay 4K 120p 10-bit 4:2:2, 16-bit RAW qua HDMI, dual-base ISO cực cao. Thiết kế cage-ready cho filmmaker chuyên nghiệp.',
    highlights: [
      'Full-frame Exmor R — chất lượng cinema tối thượng',
      '4K 120p 10-bit 4:2:2 — RAW HDMI output',
      'Dual-base ISO 800/12800 — dynamic range 15 stops',
      'Active IBIS chống rung khi quay cầm tay',
      'Tích hợp quạt tản nhiệt — quay lâu không nóng',
      'Thiết kế cage-ready với nhiều mounting points',
    ],
    specs: [
      { group: 'Cảm biến & Quay', items: [
        { label: 'Cảm biến', value: 'Full-frame Exmor R CMOS (12.1MP cho video)' },
        { label: 'Video', value: '4K 120p / FHD 240p, 10-bit 4:2:2' },
        { label: 'RAW output', value: '16-bit RAW qua HDMI Type A' },
        { label: 'Dual-base ISO', value: '800 / 12800 (S-Log3)' },
        { label: 'Log profile', value: 'S-Log3, S-Cinetone, HLG' },
      ]},
      { group: 'Vật lý & Âm thanh', items: [
        { label: 'Chống rung', value: 'Active IBIS 5 trục' },
        { label: 'Mount', value: 'Sony E' },
        { label: 'Audio', value: 'XLR Handle Unit 2-channel 24-bit' },
        { label: 'Tản nhiệt', value: 'Quạt tích hợp — quay 4K 60p không giới hạn' },
        { label: 'Trọng lượng', value: '640g (chỉ body, không pin)' },
      ]},
    ],
    packageIncludes: [
      '1× Sony FX3 body',
      '1× XLR Handle Unit',
      '1× Pin NP-FZ100',
      '1× Sạc BC-QZ1',
      '1× Cáp USB-C',
      '1× Dây đeo',
      'Phiếu bảo hành chính hãng',
    ],
    article: buildArticle({
      title: 'Đánh giá Sony FX3 — Full-frame cinema line nhỏ gọn',
      readTime: 9,
      sections: [
        { heading: 'Tổng quan', content: 'Sony FX3 là máy quay Cinema Line full-frame nhỏ gọn nhất của Sony, kết hợp chất lượng cinema với tính di động. Thiết kế cube-style, tích hợp quạt tản nhiệt, cage-ready với nhiều mounting points.' },
        { heading: 'Chất lượng cinema', content: '4K 120p 10-bit 4:2:2 nội bộ, 16-bit RAW qua HDMI. Dual-base ISO 800/12800 cho dynamic range 15 stops — chi tiết cả trong vùng tối và sáng. S-Cinetone màu đẹp ngay khi quay.' },
        { heading: 'Tính năng chuyên nghiệp', content: 'XLR Handle đi kèm cho audio chuyên nghiệp. Active IBIS 5 trục chống rung. Quay 4K 60p liên tục không giới hạn nhờ quạt tản nhiệt. Mounting points chuẩn 1/4-20 cho cage.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Full-frame cinema line nhỏ gọn. RAW output 16-bit. Active IBIS. Tản nhiệt tốt. XLR tích hợp.\n\n**Nhược điểm:** Không có EVF. Cần mua thêm cage/monitor cho setup chuyên nghiệp. Giá cao (79.9 triệu).' },
      ],
    }),
    variants: [
      { id: 'fx3-body', name: 'Body + XLR Handle', price: 79900000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/may-quay-sony-fx3-cinema-line_may-quay-phim-230210230000001',
    scrapedAt: '2026-07-09',
  },

  // ── 3. Canon C70 Cinema EOS ───────────────────────────────────────────
  {
    id: 'p20',
    slug: 'canon-c70-cinema-eos',
    name: 'Canon EOS C70 Cinema Camera — Body',
    thumbnail: `${CDN}/image-data/san-pham/24-08/24-08-29/240829180801135/avatar/canon-c70-cinema-camera.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/24-08/24-08-29/240829180801135/avatar/canon-c70-cinema-camera.jpg`,
      [],
      'Canon EOS C70',
    ),
    price: 69500000,
    originalPrice: 69500000,
    badges: [{ type: 'hot', label: 'Cinema EOS' }, { type: 'new', label: 'Chính hãng' }],
    rating: { average: 4.8, count: 22 },
    isUsed: false,
    brand: 'Canon',
    mount: 'Canon RF',
    availability: 'in_stock',
    category: 'may-quay-phim',
    shortSpecs: [
      'Super 35 DGO 4K',
      'Dual Gain Output',
      '16+ stops dynamic range',
      '4K 120p / 2K 180p',
      'Cinema RAW Light',
      'RF Mount',
    ],
    description: 'Canon EOS C70 — máy quay Cinema EOS nhỏ gọn với cảm biến Super 35 DGO 4K, dynamic range 16+ stops, Cinema RAW Light, RF Mount cho phép dùng lens RF ngàm mới nhất.',
    highlights: [
      'Cảm biến Super 35 DGO 4K — dynamic range 16+ stops',
      'Cinema RAW Light nội bộ',
      '4K 120p / 2K 180p slow motion',
      'RF Mount — dùng lens RF cao cấp',
    ],
    specs: [
      { group: 'Cảm biến & Quay', items: [
        { label: 'Cảm biến', value: 'Super 35 DGO CMOS' },
        { label: 'Video', value: '4K 120p / 2K 180p' },
        { label: 'Codec', value: 'Cinema RAW Light, XF-AVC, MP4' },
        { label: 'Dynamic Range', value: '16+ stops' },
        { label: 'Dual Gain Output', value: 'Có — giảm noise vùng tối' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Mount', value: 'Canon RF (tương thích EF qua adapter)' },
        { label: 'Kích thước', value: '160 × 116 × 116 mm' },
        { label: 'Trọng lượng', value: '1.43 kg' },
        { label: 'Pin', value: 'BP-A30 (khoảng 170 phút)' },
      ]},
    ],
    packageIncludes: [
      '1× Canon EOS C70',
      '1× Pin BP-A30',
      '1× Sạc CG-A10',
      '1× Mic Mount',
      '1× Dây đeo',
    ],
    article: buildArticle({
      title: 'Đánh giá Canon EOS C70 — Cinema EOS RF Mount nhỏ gọn',
      readTime: 8,
      sections: [
        { heading: 'Tổng quan', content: 'Canon EOS C70 là máy quay Cinema EOS nhỏ gọn với cảm biến Super 35 DGO 4K, dynamic range 16+ stops, Cinema RAW Light, RF Mount. Lựa chọn cinema ngàm RF cho filmmaker.' },
        { heading: 'Cảm biến DGO', content: 'Công nghệ Dual Gain Output cho dynamic range 16+ stops — vùng tối chi tiết, vùng sáng không cháy. Cinema RAW Light 10-bit nội bộ giữ chất lượng cao, dung lượng vừa phải.' },
        { heading: 'RF Mount Cinema', content: 'RF Mount cho phép dùng lens RF cao cấp nhất Canon. Adapter EF-EOS R tương thích lens EF cũ. Quay 4K 120p / 2K 180p slow motion — lý tưởng cho cinematic shot.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** DGO 16+ stops. Cinema RAW Light. RF Mount. 4K 120p.\n\n**Nhược điểm:** Super 35 không có low-light như full-frame. Nặng 1.43kg. Không có EVF.' },
      ],
    }),
    variants: [
      { id: 'c70-body', name: 'Body', price: 69500000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/canon-c70-cinema-camera_may-quay-phim-240829180801135',
    scrapedAt: '2026-07-09',
  },

  // ── 4. Blackmagic Pocket 6K G2 ────────────────────────────────────────
  {
    id: 'p21',
    slug: 'blackmagic-pocket-cinema-6k-g2',
    name: 'Blackmagic Pocket Cinema Camera 6K G2',
    thumbnail: `${CDN}/image-data/san-pham/23-02/23-02-10/230210230000002/avatar/01_blackmagic-pocket-6k-g2.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/23-02/23-02-10/230210230000002/avatar/01_blackmagic-pocket-6k-g2.jpg`,
      [],
      'Blackmagic Pocket Cinema 6K G2',
    ),
    price: 45900000,
    originalPrice: 45900000,
    badges: [{ type: 'hot', label: 'Cinema giá tốt' }, { type: 'new', label: 'Blackmagic' }],
    rating: { average: 4.7, count: 28 },
    isUsed: false,
    brand: 'Blackmagic',
    mount: 'Canon EF',
    availability: 'in_stock',
    category: 'may-quay-phim',
    shortSpecs: [
      'Super 35 HDR 6K',
      '13 stops dynamic range',
      '6K 60p / 4K 120p',
      'Blackmagic RAW',
      'EF Mount',
      'Pin NP-F570',
    ],
    description: 'Blackmagic Pocket Cinema Camera 6K G2 — máy quay Super 35 6K HDR, dynamic range 13 stops, Blackmagic RAW, EF Mount. Cinema chuyên nghiệp giá phải chăng.',
    highlights: [
      'Super 35 6K HDR sensor',
      'Blackmagic RAW codec',
      '6K 60p / 4K 120p',
      'LCD 5" cảm ứng 1500 nit',
    ],
    specs: [
      { group: 'Cảm biến & Quay', items: [
        { label: 'Cảm biến', value: 'Super 35 HDR 6K' },
        { label: 'Video', value: '6K 60p / 4K 120p' },
        { label: 'Codec', value: 'Blackmagic RAW, ProRes' },
        { label: 'Dynamic Range', value: '13 stops' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Mount', value: 'Canon EF' },
        { label: 'LCD', value: '5" cảm ứng, 1500 nit' },
        { label: 'Trọng lượng', value: '1.21 kg' },
        { label: 'Pin', value: 'NP-F570 (khoảng 60 phút)' },
      ]},
    ],
    packageIncludes: [
      '1× Blackmagic Pocket 6K G2',
      '1× Pin NP-F570',
      '1× Sạc',
      '1× Cáp USB-C',
      '1× Da strap',
    ],
    article: buildArticle({
      title: 'Đánh giá Blackmagic Pocket 6K G2 — Cinema 6K giá phải chăng',
      readTime: 7,
      sections: [
        { heading: 'Tổng quan', content: 'Blackmagic Pocket Cinema Camera 6K G2 là máy quay Super 35 6K HDR với Blackmagic RAW, EF Mount, LCD 5" cảm ứng 1500 nit. Cinema chuyên nghiệp ở phân khúc giá tốt nhất.' },
        { heading: '6K HDR Sensor', content: 'Super 35 6K HDR sensor với 13 stops dynamic range. Blackmagic RAW codec — chất lượng cao, dung lượng thấp hơn ProRes. 6K 60p / 4K 120p, BRAW 3:1 đến 12:1.' },
        { heading: 'LCD 5" 1500 nit', content: 'Màn hình LCD 5" cảm ứng độ sáng 1500 nit — nhìn rõ dưới nắng. Giao diện Blackmagic OS quen thuộc. EF Mount tương thích lens Canon EF/EF-S phổ biến.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** 6K 60p / 4K 120p BRAW. LCD 5" 1500 nit. EF Mount phổ biến. Giá tốt.\n\n**Nhược điểm:** Pin NP-F570 yếu (~60 phút). Không có EVF. AF chậm hơn Sony/Canon.' },
      ],
    }),
    variants: [
      { id: 'bmpcc6kg2-body', name: 'Body Only', price: 45900000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/blackmagic-pocket-cinema-6k-g2_may-quay-phim-230210230000002',
    scrapedAt: '2026-07-09',
  },
];