import type { ProductSummary } from '../types';
import { imgs, COMMON_HOTLINE, buildArticle, mavic4Paths, air3sPaths } from './utils';

const CDN = 'https://mayanhvietnam.com';

export const flycam: ProductSummary[] = [
  // ── 1. DJI Mavic 4 Pro 512GB Creator Combo ──────────────────────────────
  {
    id: 'p4',
    slug: 'dji-mavic-4-pro-512gb-creator-combo',
    name: 'DJI Mavic 4 Pro 512GB Creator Combo',
    thumbnail: mavic4Paths.avatar,
    images: imgs(mavic4Paths.avatar, mavic4Paths.previews, 'DJI Mavic 4 Pro Creator Combo'),
    price: 85000000,
    originalPrice: 85000000,
    callForPrice: true,
    badges: [{ type: 'hot', label: 'Flagship' }, { type: 'new', label: 'Mới 100%' }],
    rating: { average: 4.9, count: 142 },
    isUsed: false,
    brand: 'DJI',
    availability: 'in_stock',
    category: 'flycam',
    shortSpecs: [
      'Hasselblad 100MP 4/3 CMOS',
      '6K HDR 60fps / 4K 60fps tele',
      'LiDAR APAS 5.0 đa hướng',
      'O4+ 15km truyền sóng',
      'Bay 35-40 phút',
      'Gimbal xoay 360°',
      'RC Pro 2 điều khiển',
      '512GB tích hợp',
    ],
    description:
      'Chiếc flycam không chỉ là thiết bị bay — là cỗ máy sáng tạo thực thụ, mở ra vô vàn khả năng cho nhà làm phim, nhiếp ảnh gia chuyên nghiệp. Combo đầy đủ với bộ điều khiển DJI RC Pro 2 và dung lượng lưu trữ 512GB tích hợp.',
    highlights: [
      'Cụm 3 camera: Hasselblad 100MP CMOS 4/3 + 2 camera tele 1/1.3"',
      'Video HDR 6K/60fps (camera chính) + 4K/60fps (tele)',
      'Cảm biến LiDAR đa hướng — bay đêm 0.1-Lux cực an toàn',
      'APAS 5.0 tránh chướng ngại vật 360°',
      'O4+ truyền sóng 15km (FCC)',
      'Pin thông minh bay 35-40 phút',
      'Gimbal xoay 360° cho video cinematic',
      'ActiveTrack 5.0 + MasterShots + QuickShots',
    ],
    specs: [
      {
        group: 'Camera',
        items: [
          { label: 'Cụm 3 camera', value: '1× Hasselblad CMOS 4/3 100MP + 2× Tele CMOS 1/1.3"' },
          { label: 'Ảnh tĩnh', value: '100MP (camera chính) / 50MP (tele)' },
          { label: 'Video 6K HDR', value: '60fps (camera chính)' },
          { label: 'Video 4K HDR', value: '60fps (tele)' },
          { label: 'Video 1080p', value: '120fps slow motion' },
          { label: 'Gimbal', value: '3 trục, xoay 360°' },
        ],
      },
      {
        group: 'Bay',
        items: [
          { label: 'Thời gian bay', value: '35 - 40 phút (tùy điều kiện)' },
          { label: 'Truyền sóng', value: 'O4+ — 15km (FCC)' },
          { label: 'Tránh vật cản', value: 'APAS 5.0 đa hướng + LiDAR phía trước' },
          { label: 'Tính năng', value: 'ActiveTrack 5.0, MasterShots, QuickShots' },
        ],
      },
      {
        group: 'Lưu trữ & Combo',
        items: [
          { label: 'Bộ nhớ trong', value: '512GB tích hợp' },
          { label: 'Drone', value: '1× DJI Mavic 4 Pro 512GB' },
          { label: 'Bộ điều khiển', value: '1× DJI RC Pro 2 (màn hình tích hợp)' },
          { label: 'Pin', value: '3× Intelligent Flight Battery' },
          { label: 'Phụ kiện', value: '4× Propellers (Pair), Storage Cover, Shoulder Bag, Parallel Charging Hub' },
        ],
      },
    ],
    packageIncludes: [
      '1× DJI Mavic 4 Pro 512GB',
      '1× DJI RC Pro 2',
      '3× Intelligent Flight Battery',
      '4× Spare Propellers (Pair)',
      '1× Storage Cover',
      '1× USB-C to USB-C High-Speed Data Cable',
      '1× 240W Power Adapter',
      '1× DJI Mavic Shoulder Bag',
      '1× Parallel Charging Hub',
    ],
    article: buildArticle({
      title: 'Đánh giá DJI Mavic 4 Pro 512GB Creator Combo — Flycam flagship cho filmmaker',
      readTime: 9,
      sections: [
        { heading: 'Tổng quan', content: 'DJI Mavic 4 Pro 512GB Creator Combo là chiếc flycam cao cấp nhất DJI tính đến thời điểm hiện tại, được thiết k�� cho nhà làm phim và nhiếp ảnh gia chuyên nghiệp. Với camera Hasselblad 100MP, gimbal xoay 360°, bộ nhớ 512GB tích hợp và điều khiển RC Pro 2, đây là studio bay hoàn chỉnh.' },
        { heading: 'Camera Hasselblad 100MP', content: 'Cụm 3 camera: camera chính Hasselblad CMOS 4/3 100MP + 2 camera tele 1/1.3" cho phép zoom lossless 24-70mm equivalent. Video HDR 6K/60fps, 4K/60fps tele, 1080p 120fps slow motion.' },
        { heading: 'Tính năng bay', content: 'Thời gian bay 35-40 phút. Tránh vật cản APAS 5.0 đa hướng kết hợp LiDAR phía trước — bay đêm an toàn ở 0.1-Lux. O4+ truyền sóng 15km. ActiveTrack 5.0, MasterShots, QuickShots.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Camera Hasselblad 100MP — chất lượng hàng đầu. Gimbal 360° cinematic. RC Pro 2 màn hình tích hợp. 512GB trong. Pin 35-40 phút.\n\n**Nhược điểm:** Giá rất cao (85 triệu call for price). Nặng — khó mang đi xa. Cần học cách dùng RC Pro 2.' },
      ],
    }),
    variants: [
      { id: 'mavic4pro-creator', name: 'Creator Combo 512GB', price: 85000000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/dji-mavic-4-pro-512gb-creator-combo_flycam-250515085035248',
    scrapedAt: '2026-07-09',
  },

  // ── 2. DJI Mini 5 Pro Base ─────────────────────────────────────────────
  {
    id: 'p12',
    slug: 'dji-mini-5-pro-base-chinh-hang',
    name: 'DJI Mini 5 Pro Base — Chính hãng',
    thumbnail: `${CDN}/image-data/san-pham/25-09/25-09-12/250912094317313/avatar/638932671190111464_dji-mini-5-pro-base-chinh-hang.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/25-09/25-09-12/250912094317313/avatar/638932671190111464_dji-mini-5-pro-base-chinh-hang.jpg`,
      [],
      'DJI Mini 5 Pro',
    ),
    price: 13990000,
    originalPrice: 13990000,
    badges: [{ type: 'new', label: 'Mới' }, { type: 'hot', label: '249g' }],
    rating: { average: 4.8, count: 72 },
    isUsed: false,
    brand: 'DJI',
    availability: 'in_stock',
    category: 'flycam',
    shortSpecs: [
      '249g — không cần đăng ký tại VN',
      '1/1.3" CMOS 48MP',
      'O4 Transmission 20km',
      'Bay 34 phút',
      'APAS 5.0 omnidirectional',
      '4K 60fps HDR',
    ],
    highlights: [
      '249g — không cần đăng ký tại VN',
      'Cảm biến 1/1.3" CMOS — 4K/60fps HDR',
      'O4 Transmission — 20km siêu xa',
      'APAS omnidirectional — tránh vật cản 360°',
    ],
    specs: [
      { group: 'Camera', items: [
        { label: 'Cảm biến', value: '1/1.3" CMOS — 48MP' },
        { label: 'Khẩu', value: 'f/1.7 — FOV 82°' },
        { label: 'Video', value: '4K 60fps HDR / FHD 100fps' },
      ]},
      { group: 'Bay', items: [
        { label: 'Thời gian', value: '34 phút' },
        { label: 'Tốc độ', value: '57.6 km/h' },
        { label: 'Tránh vật cản', value: 'APAS 5.0 omnidirectional' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Trọng lượng', value: '249g' },
        { label: 'Kích thước', value: 'Gấp: 148×90×66 mm' },
        { label: 'Truyền sóng', value: 'O4 — 20km (FCC)' },
      ]},
    ],
    packageIncludes: [
      '1× DJI Mini 5 Pro',
      '1× Pin',
      '1× RC-N2 Controller',
      '1× Cáp USB-C',
      'Phiếu bảo hành chính hãng',
    ],
    variants: [
      { id: 'mini5-base', name: 'Base (RC-N2)', price: 13990000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/dji-mini-5-pro-base-chinh-hang_flycam-250912094317313',
    scrapedAt: '2026-07-09',
  },

  // ── 3. DJI Air 3S Fly More Combo ───────────────────────────────────────
  {
    id: 'p14',
    slug: 'flycam-dji-air-3s-fly-more-combo-dji-rc-2-chinh-hang',
    name: 'Flycam DJI Air 3S Fly More Combo (DJI RC 2) — Chính hãng',
    thumbnail: air3sPaths.avatar,
    images: imgs(air3sPaths.avatar, air3sPaths.previews.slice(0, 5), 'DJI Air 3S Fly More Combo'),
    price: 32990000,
    originalPrice: 32990000,
    badges: [{ type: 'hot', label: 'Tầm trung mạnh nhất' }, { type: 'new', label: 'Mới' }],
    rating: { average: 4.8, count: 35 },
    isUsed: false,
    brand: 'DJI',
    availability: 'in_stock',
    category: 'flycam',
    shortSpecs: [
      '2 camera: 1" CMOS + tele',
      '4K 100fps slow motion',
      'Bay 46 phút',
      'Omnidirectional sensing',
      'DJI RC 2 điều khiển',
    ],
    highlights: [
      'Flycam 2 camera tầm trung mạnh nhất — cảm biến 1 inch',
      '4K 100fps slow motion',
      'Bay 46 phút — pin dung lượng cao',
      'Tránh vật cản omnidirectional',
    ],
    specs: [
      { group: 'Camera', items: [
        { label: 'Cảm biến', value: '1" CMOS + tele 1/2"' },
        { label: 'Video', value: '4K 100fps / 4K 60fps HDR' },
        { label: 'Chống rung', value: '3-axis gimbal + EIS' },
      ]},
      { group: 'Bay', items: [
        { label: 'Thời gian bay', value: '46 phút' },
        { label: 'Tránh vật cản', value: 'Omnidirectional APAS 5.0' },
        { label: 'Truyền sóng', value: 'O4 — 20km' },
      ]},
      { group: 'Combo & Vật lý', items: [
        { label: 'RC', value: 'DJI RC 2 screen controller' },
        { label: 'Pin', value: '3 pin (Fly More Combo)' },
        { label: 'Trọng lượng', value: '720g' },
      ]},
    ],
    packageIncludes: [
      '1× DJI Air 3S',
      '1× DJI RC 2',
      '3× Intelligent Flight Battery',
      '1× Charging Hub',
      '6× Cánh quạt dự phòng',
      '1× Shoulder Bag',
      'Cáp sạc + hướng dẫn',
    ],
    article: buildArticle({
      title: 'Đánh giá DJI Air 3S — Flycam tầm trung mạnh nhất với camera 1 inch',
      readTime: 8,
      sections: [
        { heading: 'Tổng quan', content: 'DJI Air 3S là flycam tầm trung cao cấp nhất của DJI, với camera cảm biến 1 inch cho chất lượng ảnh vượt trội so với các dòng mini. 2 camera (chính + tele), 4K 100fps slow motion, bay 46 phút và omnidirectional sensing.' },
        { heading: 'Camera 2 ống kính', content: 'Camera chính 1" CMOS 50MP, camera tele 1/2" cho zoom lossless. 4K 100fps slow motion, 4K 60fps HDR. Chế độ MasterShots, QuickShots, ActiveTrack 5.0.' },
        { heading: 'Tính năng bay', content: 'Bay 46 phút — pin dung lượng cao nhất phân khúc. APAS 5.0 omnidirectional — tránh vật cản 360°. O4 Transmission 20km. Đèn LED beacon bay đêm an toàn.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** Camera 1" cho ảnh/video chất lượng cao. 2 camera zoom linh hoạt. Bay 46 phút. Omnidirectional sensing.\n\n**Nhược điểm:** Nặng 720g — không bỏ túi. Giá cao hơn Air 3. Cần FAA registration ở một số nơi.' },
      ],
    }),
    variants: [
      { id: 'air3s-fmc', name: 'Fly More Combo (RC 2)', price: 27990000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/flycam-dji-air-3s-fly-more-combo-dji-rc-2-chinh-hang_flycam-241102144506281',
    scrapedAt: '2026-07-10',
  },

  // ── 4. DJI Mavic Air 2 ────────────────────────────────────────────────
  {
    id: 'p15',
    slug: 'flycam-dji-mavic-air-2-chinh-hang',
    name: 'Flycam DJI Mavic Air 2 — Chính hãng',
    thumbnail: `${CDN}/image-data/san-pham/23-02/23-02-12/230212121212567/avatar/01_flycam-dji-mavic-air-2-chinh-hang.jpg`,
    images: imgs(
      `${CDN}/image-data/san-pham/23-02/23-02-12/230212121212567/avatar/01_flycam-dji-mavic-air-2-chinh-hang.jpg`,
      [],
      'DJI Mavic Air 2',
    ),
    price: 12990000,
    originalPrice: 14990000,
    badges: [{ type: 'sale', label: '-13%' }, { type: 'hot', label: 'Tầm trung' }],
    rating: { average: 4.8, count: 156 },
    isUsed: false,
    brand: 'DJI',
    availability: 'in_stock',
    category: 'flycam',
    shortSpecs: [
      '1/2" CMOS 48MP',
      '4K 60fps',
      'OcuSync 2.0 10km',
      'Bay 34 phút',
      'ActiveTrack 3.0',
      '570g',
    ],
    description: 'Flycam DJI Mavic Air 2 — cảm biến 1/2 inch CMOS 48MP, quay video 4K 60fps, OcuSync 2.0 truyền sóng 10km, bay 34 phút, ActiveTrack 3.0. Lựa chọn tầm trung lý tưởng.',
    highlights: [
      'Cảm biến CMOS 1/2 inch, chụp ảnh 48 Megapixel',
      'Quay video 4K UHD @ 60fps / Full HD @ 240fps',
      'Công nghệ truyền sóng OcuSync 2.0 xa đến 10km',
      'Thời gian bay tối đa lên tới 34 phút',
      'Hỗ trợ chế độ chụp 8K Hyperlapse',
      'ActiveTrack 3.0 bám nét thông minh',
    ],
    specs: [
      { group: 'Camera', items: [
        { label: 'Cảm biến', value: '1/2 inch CMOS — 48MP' },
        { label: 'FOV', value: '84° (tương đương 24mm)' },
        { label: 'Khẩu độ', value: 'f/2.8' },
        { label: 'Video', value: '4K 60fps / FHD 240fps' },
        { label: 'Chống rung', value: 'Gimbal 3 trục' },
      ]},
      { group: 'Bay', items: [
        { label: 'Thời gian bay', value: '34 phút' },
        { label: 'Tốc độ tối đa', value: '68.4 km/h (Sport Mode)' },
        { label: 'Truyền sóng', value: 'OcuSync 2.0 (10 km)' },
        { label: 'Kháng gió', value: 'Cấp 5 (8.5-10.5 m/s)' },
      ]},
      { group: 'Vật lý', items: [
        { label: 'Trọng lượng', value: '570g' },
        { label: 'Kích thước gấp', value: '180×97×84 mm' },
        { label: 'Dung lượng pin', value: '3500 mAh' },
      ]},
    ],
    packageIncludes: [
      '1× DJI Mavic Air 2',
      '1× Bộ điều khiển từ xa',
      '1× Pin bay thông minh',
      '3× Cặp cánh quạt dự phòng',
      '1× Cáp USB-C / Lightning / Micro-USB',
      '1× Nắp bảo vệ Gimbal',
    ],
    article: buildArticle({
      title: 'Đánh giá DJI Mavic Air 2 — Flycam tầm trung đột phá',
      readTime: 7,
      sections: [
        { heading: 'Tổng quan', content: 'DJI Mavic Air 2 mang đến đột phá mạnh mẽ trong phân khúc flycam tầm trung. Với cảm biến 1/2 inch CMOS 48MP, 4K 60fps, OcuSync 2.0 10km và 34 phút bay, đây là lựa chọn lý tưởng cho người mới bắt đầu và photographer cần flycam linh hoạt.' },
        { heading: 'Camera 48MP 4K 60fps', content: 'Cảm biến 1/2 inch cho ảnh 48MP ấn tượng. 4K 60fps mượt, FHD 240fps slow motion. 8K Hyperlapse cho time-lapse bay. HDR Video, SmartPhoto HDR tự động.' },
        { heading: 'Tính năng bay', content: '34 phút bay — dài nhất phân khúc tầm trung. OcuSync 2.0 10km — tín hiệu ổn định. ActiveTrack 3.0 bám nét thông minh. APAS 3.0 tránh vật cản.' },
        { heading: 'Ưu và nhược điểm', content: '**Ưu điểm:** 4K 60fps chất lượng cao. 48MP ảnh tĩnh. 34 phút bay. OcuSync 2.0 10km.\n\n**Nhược điểm:** Không có omnidirectional sensing. Chỉ có APAS forward/backward. Remote không có màn hình tích hợp.' },
      ],
    }),
    variants: [
      { id: 'mavicair2-std', name: 'Standard Combo', price: 12990000 },
    ],
    hotline: COMMON_HOTLINE,
    sourceUrl: 'https://mayanhvietnam.com/san-pham/flycam-dji-mavic-air-2-chinh-hang_flycam-230212121212567',
    scrapedAt: '2026-07-09',
  },
];
